### ISSUE TITLE
exporter for 1.3.1

### ISSUE THREAD

**Issue by itshikanov** [aiven/prometheus-exporter-plugin-for-opensearch#36]
Hello. I am were Update opensearch to 1.3.1 version and get this error.
```
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [prometheus-exporter] was built for OpenSearch version 1.3.0 but version 1.3.1 is running
	at org.opensearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:392)
	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:815)
	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

**Comment by lukas-vlcek** [comment]
Hi,

thanks for quick heads up.

I am checking https://github.com/opensearch-project/opensearch-build/issues/1805 and as of writing this ticket is still green (WIP) despite the OpenSearch 1.3.1 download artifacts are already available. We will release new version of the plugin once the release ticket is resolved (just in case). Stay tuned...

Regards,
Lukáš

**Comment by lukas-vlcek** [comment]
Done, see https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/issues/37
